language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: GHJIVUGoYdgO1ztRjy3l3aL+kQNfxL/O5jecMjF56i/8eUrfTxPz6KdJIq1Ehu1vYs3oxYMmalzZKdxFg++QOC32tl6E0IwUdR5yRDjTi/A+8TljZfhFsg3jne0TIaAj4LhHRWGrbCVrObKGh8CbaXKD6teBZ1nXFUOtm1VaSlwjIXaqbpLibb9avjNJDlavQ6kokR1n6MI9CbBy1DEb1RizwrVNdOaAlhog7hN7NGZ2lP9cN/k+vWTpFgP85MSUR4/s0NIdFKOzHptF4R4ses+PQCkHQGF/s+QjdPSVIil1KuojY0kvrDTjR+kmyqkmhOWHw4mfqo/5bU68G7zBdWQAq/u96SZNQz3b07sDIAUICZoKPXUKxvvMpdBIiEAD1AfUVjEOy0M9clSOeBOfAyIfQZY/SDsi3fk4xR10Q685adPej516yRw1tgHIfTaRcjaDS3zMY1WgSji4s3uN0fsraW6RStFG1YmfpbCOg69hx23SJZ54AkhjaRcowklcXoWmpFwXlfZsGb22NuZEWuMl/Mfn1g5SmmFboxzznQJRhX5PLKgj08foEzzx96iJ+sy78PIyHp9NHKwKSMvwj/YzwDpwz/7oXTv3xp5fpaoA8Ond9kg15zBmJ2yUJc0v7mE5xZ1YtJzR2R1aYSB9Yw8D4pv/aER0G8VLwpH1W9U=
  app: cs394-learn-react
  on:
    repo: pavilion99/cs394-learn-react
