language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: ogISVQ1Ubpgf4FAzagyzQlMnwe2k2e7vqtRLD97MoRhTBpPpYjskXj2jFDqa+EvY5X/+N5RLMpdL3+28mbvdV5GmMcn574qNrPHYAhyiX43E0OFJz7+AUzzc6XaVxhzGc2Yd+jQ0Fl+vE4B1GmyhvrNEv/WSNOzMjKugn8k7n3hQCgyOVvVmeklmsYyTMsJgFtcESZhD4LCQ1fFBRnQt82L8GJDLXU6oY4n4jSOlNHoyTWNdqvl2sBgy1+ZrmGF4W3BxUrZhf4H62RGiDihfrcHVV5JWTTK/2mjo50pbN015Al3F+XqajuB+26/KG5/7ugzxfIfFj4pt/Sq73OOQ8toJyi2lvvjY+IV63eIFQkEcUZ/Wp9onPsaD+VQba2D9vxC+6Zi9au3M1vrYFHZL/72FlW5ZMXj2hzq4vebwW4WmLJeAKtrS/e4uP6YplfCkVTB1Alc2iL+YRduqr6jrTZ4VaH3yolOvP8Vthewsg4ZFtQukTrOJXddEHqJT5+y7Hs8r9bE3FmLsfVBjn1kI+juVOTTLWsIy1Me7tdA9Vqt3DxcLtdr6CtKLq4J7Q1LIgHXVr1edPnhlPxmPBs9Nq0x/akBhQw6AlQ6NZPTea3VAw2pAqYpqiaXBzDrwNOH8yKD2qZXUqubByqHVmPRiRjsE2OEJ3wmoen+/hinJLVo=
  app: cs394-learn-react
  on:
    repo: pavilion99/cs394-learn-react
