language: node_js
deploy:
  provider: heroku
  app: cs394-learn-react
  api_key:
    secure: V7ciF99cdsEi05OI7mxRaBiPYo2EXzQb9j1hYKx/6yOIjR8m3HpOM2nY3xD5Nq3lIlYT9jwTZ1RJboGlXLPrMgQl0rRN4rV5+DblGGWYpufeu9MjOz3nKqy2P5oT/RFZW9vSMF4pQ5cOSfWaXHh9vnAq1SKE9yRGbLeTRNOo5eNR6nKxPFIcyZjjwpw2i/xbVIJrsiJVx/bxSpLAa9no6ypB7Y0BC6z45RTcg9tnWq0M35qfNoapFnGEg27CbB0niP7EueiJ8MXI3Mlrjyp+wjPcqS+hsvkmegjqZgRqBMmReW1VAqxKA8cSMw3kWztRWpk6XccbiqcHCr/aL2+naKS2hWy3Epk3G+ZeLzMEIjdhU4hRg7W0wWY5LsKBz3TUz4Gjr41qQG7yUydaIDvfjaiU1Fw3R8YdR4wr7/cS7Q3gwRHLy4/B45bilOgnKlSl370Iqw3FJQWPx0IuTP29SV2taYvxUgFq2/SjU1WRiwMnUnH00aC9zPb3qMkffivg/ancggk5Lo1ZzNvzR1euoWyaWsx3g1FAdcf4huynLDgJmWeZxdTTVDO/Dekt0cVjaMXkFVxn2iVshaxN1HQSTiBYkbP1qhoKmW2Ixz0y3ytsdpP3He3Npc9DODNONREsjmFW0diMuI9xZ7TvwKotdmubCA3CUnpg0IgbP3fSPxM=
