language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: UslquqH+4Cmj5I6wiHWyZY/U4wKKzXKM181WRMAzB43ER4cK8sMr3k2jOP96U9x/mdohd2/uaV6KExm9IFCJQGP4Q8fRomunZhuMLaUyi1iLrCplzfZmd27l3qkOIUdXFEg3rajqt0Pr7cd87F2f39EMkRpCcB1s/kBeQOPvE/HT3h4j8FWrZ3iKq+E06/EugRR2r0Usqhm0FSeQYyPIqDXO+fMGO+1qkWMHhWAnbWeqpmqV1oiE2pnrykvRJG5KSGfK9zwQTrNC9M/aH08RDgbreS9IiboRc8QA2+hNBWObhAZ7QlQICjtxHdqGDoEPmKwoygTS1B1nwfPCstU8Lowk7tfwfKj813xrsAe9DEAoyylfBYeQucLxk719alstFQJrplMN24vks9Ugi3CBtiyRJqGQQyzU2gllkmzANpNtZWZK9ouzH75PuT+UWSZQ6yuukAozjxESf9JH5Gqx+otgmldo1pppsx6haevu8GXHJPqlKd6fz8gh/aUyU/J6nzTm8ikzAY47BzZIN1hplX2gvBA7DSJcOHAFGSyeTYiUeZwujfiTUbvFSesHGIVUn51qDPVs/HOF6fF1VH8u7SlLio26quupTTS6RDFi7ZwIO42LnliAEw/A3sn/ADmz0i7Uo63jfGoD7DUI9X8YB8DBAaREdqpAlcG3QV4nYtw=
  app: cs394-learn-react
  on:
    repo: pavilion99/cs394-learn-react
